### PR TITLE
Uncontroversial typo fixes, updates

### PR DESCRIPTION
**Pull request by fredster33**
Supersedes #44 .

### CODE REVIEW

**Comment by YouHaveTrouble** [comment]
Will merge after #46 removes tuinity

**Comment by Trevo525** [comment]
Good catch on changing AdoptOpenJDK to Adoptium. If anyone is interested here is the [announcement blog post](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/).

**Comment by Trevo525** [comment]
I saw that you added DEAR but then removed it. I was going to suggest [this link](https://blog.airplane.gg/dear-configuration/) but It doesn't matter if it's being removed. 

However, I saw in the subreddit r/admincraft that a lot of people recommend Purpur. Is there any reason why it is at the bottom of the list? It might even be nice to make a list of reasons for or against each server implementation. Just a thought and I would not mind helping after this gets merged if this is something that people agree with.

Lastly, in that same section, starting from commit 4a5ec8b64b6f6f569e9c503d977ad3457f95fdf0, the new line after the last server has been removed. In the version that you merged, if you would just add a new line before "You should stay away from:" so that it isn't a part of Purpur's information line that would fix this.

**Comment by YouHaveTrouble** [comment]
> I saw in the subreddit r/admincraft that a lot of people recommend Purpur. Is there any reason why it is at the bottom of the list?

Yes. The list of suggested software is ordered by the upstream tree. Tuinity upstreams Paper, Airplane upstreams Tuinity and Purpur upstreams Airplane, that's why Purpur is at the botton of the list.

**Comment by Trevo525** [comment]
> The list of suggested software is ordered by the upstream tree. Tuinity upstreams Paper, Airplane upstreams Tuinity and Purpur upstreams Airplane, that's why Purpur is at the botton of the list.

That makes perfect sense. Just a little oversight on my part. Thanks for the explanation!

> edit: and yes, I just noticed airplane and purpur need to swap places in order for this to be true

👍

**Comment by fredster33** [comment]
> I saw that you added DEAR but then removed it. I was going to suggest [this link](https://blog.airplane.gg/dear-configuration/) but It doesn't matter if it's being removed.
Hmm? Am a bit confused here, I don't remember removing/adding DEAR.
> Lastly, in that same section, starting from commit [4a5ec8b](https://github.com/YouHaveTrouble/minecraft-optimization/commit/4a5ec8b64b6f6f569e9c503d977ad3457f95fdf0), the new line after the last server has been removed. In the version that you merged, if you would just add a new line before "You should stay away from:" so that it isn't a part of Purpur's information line that would fix this.
Added a new line.

**Comment by Trevo525** [comment]
> Hmm? Am a bit confused here, I don't remember removing/adding DEAR.

[4a5ec8b64b6f6f569e9c503d977ad3457f95fdf0](https://github.com/YouHaveTrouble/minecraft-optimization/pull/47/commits/4a5ec8b64b6f6f569e9c503d977ad3457f95fdf0) 👀 

It was removed in the very next commit though. That's why I said it doesn't really matter.

**Comment by fredster33** [comment]
Oh, that was back when I opened #44. I'll delete the commit.

**Comment by fredster33** [comment]
Git noob, but looks like that's not possible. If it's really a bother, I can delete my fork and re-fork 🤷

**Comment by Trevo525** [comment]
> Git noob, but looks like that's not possible. If it's really a bother, I can delete my fork and re-fork 🤷

Nope. Don't worry about it. You already removed it from the latest commit. I was just bringing it to light unnecessarily. You did everything right from what I can tell :-)

**Pull request merged**
